app/models/laporan.py
from datetime import datetime

from app.extensions import db
from app.models.mahasiswa import Mahasiswa


class Laporan(db.Model):
    __tablename__ = 'laporan'
    id = db.Column(db.Integer, primary_key=True)
    mahasiswa_id = db.Column(db.Integer, db.ForeignKey('mahasiswa.id'), nullable=False)
    hasil_prediksi = db.Column(db.String(50), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __init__(self, mahasiswa_id, hasil_prediksi, created_at=None, updated_at=None):
        self.mahasiswa_id = mahasiswa_id
        self.hasil_prediksi = hasil_prediksi
        self.created_at = created_at or datetime.utcnow()
        self.updated_at = updated_at or datetime.utcnow()

    def __repr__(self):
        return f"Mahasiswa('{self.id}', '{self.mahasiswa_id}', '{self.hasil_prediksi}')"

    def set_laporan(self):
        try:
            db.session.add(self)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            print(f"Error during adding Laporan: {e}")

        return self
    
    def insert_laporan(self):
        existing_record = db.session.query(Laporan).filter_by(mahasiswa_id=self.mahasiswa_id).first()

        if existing_record is None:
            db.session.add(self)
            db.session.commit()
     
    
    @staticmethod
    def get_data_laporan():
        laporan_data = (
            db.session.query(Laporan, Mahasiswa)
            .join(Mahasiswa)
            .all()
        )

        result = []
        for laporan, mahasiswa in laporan_data:
            result.append({
                'laporan_id': laporan.id,
                'mahasiswa_id': mahasiswa.id,  # Assuming you want mahasiswa's id
                'npm': mahasiswa.npm,
                'nama': mahasiswa.nama,
                'prodi': mahasiswa.prodi,
                'tahun_masuk': mahasiswa.tahun_masuk,
                'status': mahasiswa.ket_aktif,
                'prediksi': laporan.hasil_prediksi,
                'created_at': laporan.created_at,
                'updated_at': laporan.updated_at,
            })
        
        return result

app/models/mahasiswa.py
from datetime import datetime
from sqlalchemy import func, Integer
from app.extensions import db
from app.models.transkip import Transkip


class Mahasiswa(db.Model):
    __tablename__ = 'mahasiswa'
    id = db.Column(db.Integer, primary_key=True)
    npm = db.Column(db.String(255), unique=False, nullable=True)
    nama = db.Column(db.String(255))
    prodi = db.Column(db.String(255))
    tahun_masuk = db.Column(db.String(255), nullable=True)
    ket_aktif = db.Column(db.String(255), nullable=True)
    ket_lulus = db.Column(db.String(255), nullable=True)
    total_sks = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, onupdate=datetime.utcnow)
    transkip = db.relationship('Transkip', backref='mahasiswa', cascade='all, delete-orphan', lazy=True)

    def get_by_id(mahasiswa_id):
        return Mahasiswa.query.get(int(mahasiswa_id))

    def set_mahasiswa(self):
        try:
            db.session.add(self)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            print(f"Error during adding Mahasiswa: {e}")
            return None

        try:
            for semester_number in range(1, 8):
                transkip = Transkip(
                    mahasiswa_id=self.id,
                    semester=f'Semester {semester_number}',
                    ips=0.0,
                    sks=0,
                    created_at=datetime.utcnow(),
                    updated_at=datetime.utcnow()
                )
                db.session.add(transkip)
                db.session.commit()
        except Exception as e:
            db.session.rollback()
            print(f"Error during adding Transkip: {e}")
            return None

        return self

    @staticmethod
    def get_data_transkip():
        subquery = db.session.query(
            Transkip.mahasiswa_id,
            Transkip.ips,
            Transkip.sks,
            Transkip.semester
        ).order_by(Transkip.semester).subquery()

        query = db.session.query(
            Mahasiswa.id,
            Mahasiswa.npm,
            Mahasiswa.nama,
            Mahasiswa.prodi,
            func.coalesce(func.group_concat(subquery.c.ips), '0').label('ips'),
            func.coalesce(func.group_concat(subquery.c.sks), '0').label('sks'),
            func.coalesce(func.group_concat(subquery.c.semester), '0').label('semester'),
            func.cast(func.sum(subquery.c.sks), Integer).label('total_sks'),
            func.round(func.avg(subquery.c.ips), 2).label('ipk')
        ).outerjoin(subquery, Mahasiswa.id == subquery.c.mahasiswa_id).group_by(Mahasiswa.id)

        result = query.all()

        data = []
        for row in result:
            data.append({
                "id": row.id,
                "npm": row.npm,
                "nama": row.nama,
                "prodi": row.prodi,
                "ips": [float(ip) for ip in row.ips.split(',')],  # Convert Decimal to float
                "sks": [int(sk) for sk in row.sks.split(',')],  # Convert Decimal to float
                "ipk": float(row.ipk) if row.ipk else 0.0,  # Convert Decimal to float
                "total_sks": int(row.total_sks) if row.total_sks else 0  # Convert Decimal to float
            })

        return data  # Return the list of dictionaries

    @staticmethod
    def get_by_name(name):
        return Mahasiswa.query.filter(Mahasiswa.nama.like('%' + name + '%')).all()

    @staticmethod
    def get_by_name_like(term):
        return (
            db.session.query(Mahasiswa.nama)
            .filter(Mahasiswa.nama.ilike(f'%{term}%'))  # Case-insensitive search
            .limit(10)  # Optional: limit the number of results
            .all()
        )

app/controllers/mahasiswa_controller.py
from datetime import datetime
from flask import flash, redirect, url_for
from app import db
from app.forms import CreateMahasiswa
from app.models.mahasiswa import Mahasiswa


def create_mahasiswa():
    form = CreateMahasiswa()

    existing_mahasiswa = Mahasiswa.query.filter_by(npm=form.npm.data).first()
    if existing_mahasiswa:
        flash('NPM sudah digunakan oleh mahasiswa lain.', 'error')
        return redirect(url_for('main.mahasiswa'))

    mahasiswa = Mahasiswa(
        npm=form.npm.data,
        nama=form.nama.data,
        prodi=form.prodi.data,
        tahun_masuk=form.tahun_masuk.data,
        ket_aktif=form.ket_aktif.data,
        created_at=datetime.utcnow()
    )

    result = mahasiswa.set_mahasiswa()

    flash('Your account has been created!', 'success')


def edit_mahasiswa(mahasiswa_id):
    form = CreateMahasiswa()

    mahasiswa = Mahasiswa.get_by_id(mahasiswa_id)
    existing_mahasiswa = Mahasiswa.query.filter(Mahasiswa.npm == form.npm.data).first()

    if existing_mahasiswa and existing_mahasiswa.id != mahasiswa_id:
        flash('NPM sudah digunakan oleh mahasiswa lain.', 'error')
        return redirect(url_for('main.dashboard'))

    mahasiswa.npm = form.npm.data
    mahasiswa.nama = form.nama.data
    mahasiswa.prodi = form.prodi.data
    mahasiswa.ket_aktif = form.ket_aktif.data
    mahasiswa.updated_at = datetime.now()
    db.session.commit()

    flash('Your account has been updated!', 'success')


def delete_mahasiswa(mahasiswa_id):
    mahasiswa = Mahasiswa.query.get(mahasiswa_id)
    if mahasiswa:
        db.session.delete(mahasiswa)
        db.session.commit()
        flash(f'Mahasiswa dengan ID {mahasiswa_id} telah dihapus', 'success')
    else:
        flash(f'Mahasiswa dengan ID {mahasiswa_id} tidak ditemukan', 'error')

app/controllers/prediksi_controller.py
import os
from joblib import load
from app.models.transkip import Transkip

model_path = os.path.join(os.path.dirname(__file__), '..', '..', 'rf_prediksi')
model_path = os.path.abspath(model_path)


def prediksi_mahasiswa(mahasiswa_id):
    model = load(model_path)

    x = Transkip.get_data_transkip(mahasiswa_id)

    prediction = model.predict(x)

    if prediction[0] == 1:
        return 'Lulus Tepat Waktu'
    else:
        return 'Tidak Lulus Tepat Waktu'


def prediksi_mahasiswa_ipk(mhs_id):
    mahasiswa = Transkip.get_transkip_by_mhs_id(mhs_id)

    data = []
    total_ips = 0
    total_sks = 0
    total_semester = 0

    for mhs in mahasiswa:
        mhs_dict = {
            'id': mhs.id,
            'mhs_id': mhs.mahasiswa_id,
            'semester': mhs.semester,
            'ips': mhs.ips,
            'sks': mhs.sks,
        }

        data.append(mhs_dict)

        total_ips += mhs.ips
        total_sks += mhs.sks
        total_semester += 1

    meta = {
        'mhs_id': mhs_id,
        'ipk': round(total_ips / total_semester, 2),  # or format(total_ips / total_semester, '.2f')
        'total_sks': total_sks,
        'total_semester': total_semester,
    }

    return {'meta': meta, 'data': data}

app/controllers/transkip_controller.py
from flask import flash, request
from app import db
from app.models.transkip import Transkip


def edit_transkip(mahasiswa_id):
    for i in range(1, 8):
        ips_key = f'ips_{i}_{mahasiswa_id}'
        sks_key = f'sks_{i}_{mahasiswa_id}'
        semester = f'Semester {i}'

        ips_value = request.form.get(ips_key)
        sks_value = request.form.get(sks_key)

        if ips_value and sks_value:
            # Cari data nilai berdasarkan mahasiswa_id dan semester
            nilai = Transkip.query.filter_by(mahasiswa_id=mahasiswa_id, semester=semester).first()
            if nilai:
                nilai.ips = float(ips_value)
                nilai.sks = int(sks_value)
            else:
                # Buat entri baru jika tidak ditemukan
                nilai = Transkip(mahasiswa_id=mahasiswa_id, semester=semester, ips=float(ips_value),
                                 sks=int(sks_value))
                db.session.add(nilai)

        db.session.commit()
    flash('Your transkip has been updated!', 'success')

app/routes.py
import json
from flask import Blueprint, jsonify, render_template, redirect, url_for, flash, request
from . import db
from .forms import RegistrationForm, LoginForm, CreateAcount, CreateMahasiswa
from datetime import datetime
from flask_login import login_user, logout_user, login_required, current_user
from app.models.user import User
from app.controllers import user_controller, mahasiswa_controller, transkip_controller, prediksi_controller
from app.controllers import auth_controller
from .models.mahasiswa import Mahasiswa
from .models.transkip import Transkip
from .models.laporan import Laporan
import json

main = Blueprint('main', __name__)


@main.route('/')
def index():
    # form = LoginForm()
    # return render_template('login.html', form=form)
    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    if form.validate_on_submit():
        auth_controller.register()
        flash('Your account has been created!', 'success')
        return redirect(url_for('main.login'))

    return render_template('register.html', form=form)


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Login successful!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Invalid username or password', 'error')
    return render_template('login.html', form=form)  # Mengirimkan form ke template


@main.route('/dashboard')
@login_required  # Hanya pengguna yang sudah login yang bisa mengakses dashboard
def dashboard():
    return render_template('dashboard.html')


@main.route('/logout')
def logout():
    logout_user()
    flash('Logout successful!', 'success')
    return redirect(url_for('main.index'))


@main.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    # user = User.query.filter_by(role='admin').all()
    user = User.query.all()
    header = ['No', 'Username', 'Email', 'Role', 'Created At']
    title = 'Data Admin'

    form = CreateAcount()

    return render_template('admin.html', data=user, header=header, title=title, form=form)


@main.route('/add_user', methods=['POST'])
@login_required
def add_user():
    user_controller.create_user()
    flash('Your account has been created!', 'success')
    return redirect(url_for('main.admin'))


@main.route('/edit_user/<int:user_id>', methods=['POST'])
@login_required
def edit_user(user_id):
    user_controller.edit_user(user_id)
    flash('Your account has been updated!', 'success')
    return redirect(url_for('main.admin'))


@main.route('/delete_user/<int:user_id>', methods=['POST'])
@login_required
def delete_user(user_id):
    user_controller.delete_user(user_id)
    flash('Your account has been deleted!', 'success')
    return redirect(url_for('main.admin'))


@main.route('/mahasiswa', methods=['GET'])
@login_required
def mahasiswa():
    form = CreateMahasiswa()

    mahasiswa = Mahasiswa.query.all()
    header = ['No', 'NPM', 'Nama', 'Program Studi', 'Status', 'Created At']
    title = 'Data Mahasiswa'

    return render_template('mahasiswa.html', data=mahasiswa, header=header, title=title, form=form)


@main.route('/add_mahasiswa', methods=['POST'])
@login_required
def add_mahasiswa():
    mahasiswa_controller.create_mahasiswa()
    return redirect(url_for('main.mahasiswa'))


@main.route('/edit_mahasiswa/<int:mahasiswa_id>', methods=['POST'])
@login_required
def edit_mahasiswa(mahasiswa_id):
    mahasiswa_controller.edit_mahasiswa(mahasiswa_id)
    return redirect(url_for('main.mahasiswa'))


@main.route('/delete_mahasiswa/<int:mahasiswa_id>', methods=['POST'])
@login_required
def delete_mahasiswa(mahasiswa_id):
    mahasiswa_controller.delete_mahasiswa(mahasiswa_id)
    return redirect(url_for('main.mahasiswa'))


@main.route('/transkip', methods=['GET'])
@login_required
def transkip():
    form = CreateMahasiswa()

    mahasiswa = Mahasiswa.get_data_transkip()
    title = 'Data Mahasiswa'
    header = ['No', 'Nama Mahasiswa']

    if any('ips' in mhs and mhs['ips'] for mhs in mahasiswa):
        header = ['No', 'Nama Mahasiswa'] + ['IPS{}'.format(i + 1) for i in range(len(mahasiswa[0]['ips']))] + ['IPK',
                                                                                                                'SKS']
    return render_template('transkip.html', data=mahasiswa, header=header, title=title, form=form)


@main.route('/edit_transkip/<int:mahasiswa_id>', methods=['POST'])
@login_required
def edit_transkip(mahasiswa_id):
    transkip_controller.edit_transkip(mahasiswa_id)
    return redirect(url_for('main.transkip'))


@main.route('/prediksi', methods=['GET'])
@login_required
def prediksi():
    nama = request.args.get('nama')

    data = None
    data_graph = []

    if nama is not None:
        import array
        data = Mahasiswa.get_by_name(nama)

        for mhs in data:
            mhs.prediksi = prediksi_controller.prediksi_mahasiswa(mhs.id)
            get_data_graph = prediksi_controller.prediksi_mahasiswa_ipk(mhs.id)
            data_graph.append(get_data_graph)

            laporan = Laporan(mahasiswa_id=mhs.id, hasil_prediksi=mhs.prediksi)
            laporan.insert_laporan()

    json_data = json.dumps(data_graph, indent=4)

    return render_template('prediksi.html', data=data, graph=json_data)


@main.route('/prediksi/<int:mahasiswa_id>', methods=['GET'])
def prediksi_exce(mahasiswa_id):
    prediksi_controller.prediksi_mahasiswa(mahasiswa_id)
    return redirect(url_for('main.mahasiswa'))


@main.route('/delete_selected', methods=['POST'])
def delete_selected_mahasiswa():
    selected_ids = request.form.getlist('selected_ids[]')
    for mahasiswa_id in selected_ids:
        mahasiswa_controller.delete_mahasiswa(mahasiswa_id)

    return redirect(url_for('main.mahasiswa'))

@main.route('/laporan', methods=['GET'])
def laporan():
    # data = Mahasiswa.get_data_transkip()
    data = Laporan.get_data_laporan()

    return render_template('laporan.html', data=data)

@main.route('/get-nama-mahasiswa', methods=['GET'])
def get_nama_mahasiswa():   
    term = request.args.get('term')
    mahasiswa_list = Mahasiswa.get_by_name_like(term)

    names = [mhs[0] for mhs in mahasiswa_list]

    return jsonify({'names': names})

app/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Hallo {{ current_user.username if current_user.username else '' }},
                <br/> Selamat Datang
                Di Aplikasi Mahasiswa</h1>
            <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
                For more information about DataTables, please visit the.</p></div>
    </div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hallo Sayang</h1>
</body>
</html>

app/templates/mahasiswa.html
{% extends "base.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<!-- Page Heading -->
<div class="d-flex justify-content-between align-items-center mb-2">
    <h4 class="h3 mb-2 text-gray-800">{{ title }}</h4>
    <div>
        <button type="button" class="d-sm-inline-block btn btn-sm btn-info shadow-sm" data-toggle="modal"
            data-target="#modalImport">
            <i class="fas fa-plus fa-sm text-white-50"></i>
            Import XLSX
        </button>
        <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-toggle="modal"
            data-target="#exampleModalCenter">
            <i class="fas fa-plus fa-sm text-white-50"></i>
            Tambah Mahasiswa
        </button>
    </div>
</div>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <form method="POST" action="{{ url_for('main.delete_selected_mahasiswa') }}">
                {{ form.hidden_tag() }}

                <!-- Tombol untuk menghapus yang dipilih -->
                <div class="mb-3 w-100 d-flex justify-content-end align-items-center">
                    <button type="submit" class="btn btn-danger">Hapus yang Dipilih</button>
                </div>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th></th>
                            {% for head in header %}
                            <th>{{ head }}</th>
                            {% endfor %}
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in data %}
                        <tr>
                            <td><input type="checkbox" name="selected_ids[]" value="{{ user.id }}"></td>
                            <td>{{ loop.index }}</td>
                            <td>{{ user.npm }}</td>
                            <td>{{ user.nama }}</td>
                            <td>{{ user.prodi }}</td>
                            <td>{{ user.ket_aktif }}</td>
                            <td>{{ user.created_at }}</td>
                            <td>
                                <button type="button" class="btn btn-info btn-sm mx-1" data-toggle="modal"
                                    data-target="#editModal{{ user.id }}">
                                    <i class="fas fa-edit"></i>
                                </button>
                                <button type="button" class="btn btn-danger btn-sm mx-1" data-toggle="modal"
                                    data-target="#confirmDelete{{ user.id }}">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>

<!-- modal update & edit -->
{% for user in data %}
<!-- Modal Edit untuk setiap data -->
<div class="modal fade" id="editModal{{ user.id }}" tabindex="-1" role="dialog"
    aria-labelledby="editModalLabel{{ user.id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel{{ user.id }}">Edit Data
                    <span class="text-primary">{{ user.nama }}</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ url_for('main.edit_mahasiswa', mahasiswa_id=user.id) }}">
                {{ form.hidden_tag() }}

                <div class="modal-body">
                    <div class="form-group">
                        <label>NPM</label>
                        <input type="text" name="npm" class="form-control" value="{{ user.npm }}">
                        {% for error in form.npm.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label>Nama</label>
                        <input type="text" name="nama" class="form-control" value="{{ user.nama }}">
                        {% for error in form.nama.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label>Program Studi</label>
                        <input type="text" name="prodi" class="form-control" value="{{ user.prodi }}">
                        {% for error in form.prodi.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="ket_aktif">Status Mahasiswa</label>
                        <select name="ket_aktif" class="form-control" id="ket_aktif">
                            <option value="AKTIF" {% if user.ket_aktif=='AKTIF' %}selected{% endif %}>
                                Aktif
                            </option>
                            <option value="NON AKTIF" {% if user.ket_aktif=='NON AKTIF' %}selected{% endif %}>
                                Non Aktif
                            </option>
                        </select>
                        {% for error in form.ket_aktif.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                        Update
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Konfirmasi Hapus -->
<div class="modal fade" id="confirmDelete{{ user.id }}" tabindex="-1" role="dialog"
    aria-labelledby="confirmDeleteLabel{{ user.id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteLabel{{ user.id }}">Konfirmasi
                    Hapus
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Apakah Anda yakin ingin menghapus data ini?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal
                </button>
                <!-- Form untuk Menghapus Data -->
                <form method="POST" action="{{ url_for('main.delete_mahasiswa', mahasiswa_id=user.id) }}"
                    class="d-inline">
                    {{ form.hidden_tag() }}
                    <button type="submit" class="btn btn-danger">Ya, Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!-- end modal update & edit -->

{# modal #}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Tambah Mahasiswa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ url_for('main.add_mahasiswa') }}" method="POST" class="user">
                {{ form.hidden_tag() }}

                <div class="modal-body">
                    <div class="form-group">
                        <label>NPM</label>
                        {{ form.npm(class_='form-control', type='number') }}
                        {% for error in form.npm.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label>Nama</label>
                        {{ form.nama(class_='form-control') }}
                        {% for error in form.nama.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label>Prodi</label>
                        {{ form.prodi(class_='form-control') }}
                        {% for error in form.prodi.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="tahun_masuk">Tahun Masuk</label>
                        {{ form.tahun_masuk(class_='form-control', render_kw={"type": "year"}) }}
                        {% for error in form.tahun_masuk.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="role">Status Mahasiswa</label>
                        {{ form.ket_aktif(class_='form-control', id='ket_aktif') }}
                        {% for error in form.ket_aktif.errors %}
                        <small class="text-danger">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}